server:
  port: 12345

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hiddenPackages: com.alibaba
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri: redis://127.0.0.1:6379
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hxtest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: zhx2131203017
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.hxzhao.jetcachedemo: debug
    com.alicp.jetcache: debug
debug: true

